apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twentycrm-server
  name: twentycrm-server
  namespace: twentycrm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: twentycrm-server
  template:
    metadata:
      labels:
        app: twentycrm-server
    spec:
      volumes:
        - name: twentycrm-server-data
          persistentVolumeClaim:
            claimName: twentycrm-server-pvc
        - name: twentycrm-docker-data
          persistentVolumeClaim:
            claimName: twentycrm-docker-data-pvc
      initContainers:
        - name: change-vol-ownership
          image: ubuntu
          command: [ "bash", "-c", "chown -R 1000:1000 /app/docker-data /app/packages/twenty-server/.local-storage" ]
          volumeMounts:
            - name: twentycrm-docker-data
              mountPath: /app/docker-data
            - name: twentycrm-server-data
              mountPath: /app/packages/twenty-server/.local-storage
        - name: init-database
          image: max-crm:latest
          imagePullPolicy: Never
          env:
            - name: PG_DATABASE_URL
              value: "postgres://postgres:postgres@twentycrm-db.twentycrm.svc.cluster.local:5432/default"
          command:
            - yarn
            - database:init:prod
        - name: migrate
          image: max-crm:latest
          imagePullPolicy: Never
          env:
            - name: PG_DATABASE_URL
              value: "postgres://postgres:postgres@twentycrm-db.twentycrm.svc.cluster.local:5432/default"
            - name: DISABLE_DB_MIGRATIONS
              value: "false"
          command:
            - yarn
            - database:migrate:prod
      containers:
        - name: twentycrm
          image: max-crm:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "3000"
            - name: SERVER_URL
              value: "http://localhost:8080"  # need to use a domain with port 443
            - name: "PG_DATABASE_URL"
              value: "postgres://postgres:postgres@twentycrm-db.twentycrm.svc.cluster.local:5432/default"
            - name: "REDIS_URL"
              value: "redis://twentycrm-redis.twentycrm.svc.cluster.local:6379"
            - name: SIGN_IN_PREFILLED
              value: "false"
            - name: STORAGE_TYPE
              value: "local"
            - name: "MESSAGE_QUEUE_TYPE"
              value: "bull-mq"
            - name: "ACCESS_TOKEN_EXPIRES_IN"
              value: "7d"
            - name: "LOGIN_TOKEN_EXPIRES_IN"
              value: "1h"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: tokens
                  key: accessToken
          ports:
            - containerPort: 3000
              name: http-tcp
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /app/docker-data
              name: twentycrm-docker-data
            - mountPath: /app/packages/twenty-server/.local-storage
              name: twentycrm-server-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
