apiVersion: v1
kind: PersistentVolume
metadata:
  name: twentycrm-docker-data-pv
spec:
  storageClassName: default
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/twentycrm-docker-data
    type: DirectoryOrCreate